### ISSUE TITLE
Embed the live stream + interaction on the event page?

### ISSUE THREAD

**Issue by cycomachead** [snap-cloud/snapcon#64]
What would this look like. How could be have a unified text chat?

**Comment by bennettscience** [comment]
Thanks for starting this fork of the project. I'm actually using your copy as my base now instead of the main repo.

I'm also thinking about the same kind of feature. We're going to be embedding a YouTube Premiere video as the session. But, I want to have some kind of real-time interaction piece on the event page. The YouTube chat cannot be embedded outside, so it needs to be something else. I've looked at a couple ActionController apps to work chat right into the platform, but I'm not sure I want to go that route.

Have you done anything to solve this problem?

**Comment by cycomachead** [comment]
Glad this is helpful! :) I may at some point borrow some of your code from the Canvas or PD apps. :) 
Fair warning, as you've probably noticed, there's some Snap!-specific styling throughout the app (https://snapcon.org) -- mostly the little trapezoidal cutouts in a few places. There are also a couple places where I have significantly relaxed the markdown security. Mostly this seems fine since it's admins writing content, but technically it can apply to event proposals. 


I never made progress on this -- though, perhaps a basic page that iframes would have been enough since we're primarily in Zoom -- but there the desktop app is better. 

For youtube, it seems like embedding the chat is possible, though you'd need a proxy if you didn't want to require a Google login. (https://www.peggyktc.com/2016/05/embed-livestream-and-chat.html)

We use Discourse

**Comment by bennettscience** [comment]
Yeah, I've started going through your fork and cleaning it up for our templates. I made some changes to make it easier for registrants to find the schedule from the user menu that I want to keep. Thanks for the link on the YouTube chat. Since we'll have everything set up ahead of time, it should be easy to build that into the templates.

**Comment by cycomachead** [comment]
It's been a super long time, but I finally got around to building a very basic page.
a Room now supports a `url` and `discussion_url`, and if present you can go to `/conferences/:short_name/rooms/:room_id/live_session` to see a split view with the two pages embedded. 

I think there's more work to make this easy for other services, but maybe it's helpful.
